// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuWTEccKYbg-XWglf0IYCJUHSiTOm3lww',
    appId: '1:305634903844:web:41f9c613e9066fa2c015b1',
    messagingSenderId: '305634903844',
    projectId: 'retrieva-65b1c',
    authDomain: 'retrieva-65b1c.firebaseapp.com',
    storageBucket: 'retrieva-65b1c.firebasestorage.app',
    measurementId: 'G-VH34LGL4RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQzWd1no8WuxRWjfpRyclMJ_4VDyLnYpA',
    appId: '1:305634903844:android:7184d5ce03b71be6c015b1',
    messagingSenderId: '305634903844',
    projectId: 'retrieva-65b1c',
    storageBucket: 'retrieva-65b1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIk_0uUTRDUOat1Aa0ZqPYbxmtIsy9BI8',
    appId: '1:305634903844:ios:9dd7a95c0606096ac015b1',
    messagingSenderId: '305634903844',
    projectId: 'retrieva-65b1c',
    storageBucket: 'retrieva-65b1c.firebasestorage.app',
    iosBundleId: 'com.example.retrieva',
  );
}
